#!/usr/bin/env bash

waitForMongoDB() {
        while true; do
                status=$(mongo ${MONGODB_ADDRESS}/admin -u root -p ${MONGODB_ROOT_PASSWORD} --eval "db.adminCommand('ping')" | tail -n1)

                echo "MongoDB status = $status"
                [ "$status" == '{ "ok" : 1 }' ] && break

                echo "Sleeping 10 seconds ..."
                sleep 10

        done
}


if [[ -z "${MONGODB_ADDRESS}" || -z "${MONGODB_DATABASE}" || -z "${MONGODB_USER}" || -z "${MONGODB_PASSWORD}" || -z "${MONGODB_ROOT_PASSWORD}" ]]; then
       echo "Some of the variables are not defined correctly. Check them out !"
       exit 1
fi

waitForMongoDB

mongo ${MONGODB_ADDRESS}/admin -u root -p ${MONGODB_ROOT_PASSWORD} --eval "db.getSiblingDB('${MONGODB_DATABASE}').createUser({user: '${MONGODB_USER}', pwd: '${MONGODB_PASSWORD}', roles: ['readWrite']})"

if [ $? == 0 ]; then
  mongoimport --host ${MONGODB_ADDRESS} --db ${MONGODB_DATABASE} --username ${MONGODB_USER} --password ${MONGODB_PASSWORD} --collection accounts --type json --file /etc/admin/accounts.json
else
  echo "Something went wrong !" && exit 1
fi

if [ $? == 0 ]; then
  mongoimport --host ${MONGODB_ADDRESS} --db ${MONGODB_DATABASE} --username ${MONGODB_USER} --password ${MONGODB_PASSWORD} --collection users --type json --file /etc/admin/users.json
else
  echo "Something went wrong !" && exit 1
fi

if [ $? == 0 ]; then
  mongoimport --host ${MONGODB_ADDRESS} --db ${MONGODB_DATABASE} --username ${MONGODB_USER} --password ${MONGODB_PASSWORD} --collection idps --type json --file /etc/admin/idps.json
else
  echo "Something went wrong !" && exit 1
fi
