#! /bin/bash

# This script relates to CR-2982
# Sets https://docs.mongodb.com/manual/reference/command/setFeatureCompatibilityVersion/#dbcmd.setFeatureCompatibilityVersion
# for the mongo database

set -xeuo pipefail

if env | grep MONGODB_SERVICE_HOST; then
    mongosh --host $MONGO_SERVICE:27017 -u root -p $MONGODB_ROOT_PASSWORD --eval "db.adminCommand( { setFeatureCompatibilityVersion: \"$MONGO_COMPAT_VERSION\" } )"
fi
