{{- if .Values.global.mongoTLS }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-mongodb-tls
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ca.pem: {{ printf "%s%s" .Values.mongoTLS.CaCert .Values.mongoTLS.CaKey | b64enc }}
{{- end }}