---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codefresh.fullname" . }}-registry
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "codefresh.imagePullSecret" . }}
---
{{- if index .Values "argo-platform" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "codefresh.imagePullSecret" . }}
{{- end }}