apiVersion: v1
kind: Secret
metadata:
    name: {{ template "fullname" . }}
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
    annotations:
      "helm.sh/hook": "pre-install"
      "helm.sh/hook-weight": "23"
type: Opaque
data:
    # Mongodb credentials
    mongodb-user: {{ default "cfuser" .Values.global.mongodbUsername | b64enc | quote }}
    {{ if .Values.global.mongodbPassword }}
    mongodb-password:  {{ .Values.global.mongodbPassword | b64enc | quote }}
    {{ else }}
    mongodb-password: {{ randAlphaNum 14 | b64enc | quote }}
    {{ end }}

    # RabbitMQ credentials
    rabbitmq-username: {{ default "user" .Values.rabbitmq.rabbitmqUsername | b64enc | quote }}
    {{ if .Values.rabbitmq.rabbitmqPassword }}
    rabbitmq-password:  {{ .Values.rabbitmq.rabbitmqPassword | b64enc | quote }}
    {{ else }}
    rabbitmq-password: {{ randAlphaNum 14 | b64enc | quote }}
    {{ end }}

    # PostgreSQL credentials
    postgres-user: {{ default "user" .Values.postgresql.postgresUser | b64enc | quote }}
    {{ if .Values.postgresql.postgresPassword }}
    postgres-password:  {{ .Values.postgresql.postgresPassword | b64enc | quote }}
    {{ else }}
    postgres-password: {{ randAlphaNum 14 | b64enc | quote }}
    {{ end }}

    # Redis credentials
    {{ if .Values.redis.redisPassword }}
    redis-password:  {{ .Values.redis.redisPassword | b64enc | quote }}
    {{ else }}
    redis-password: {{ randAlphaNum 14 | b64enc | quote }}
    {{ end }}

    # GitHub secrets
    github-internal-token: {{ default "" .Values.githubInternalToken | b64enc | quote }}
    
    # 
    api-safe-secret: {{ default "" .Values.apiSafeSecret | b64enc | quote }}

    # Stripe secret
    stripe-secret-key: {{ default "" .Values.stripeSecretKey | b64enc | quote }}
    # Stripe public key
    stripe-public-key: {{ default "" .Values.stripePublicKey | b64enc | quote }} 
    # Stripe webhook sign secret
    stripe-webhook-sign-secret: {{ default "" .Values.stripeWebhookSecret | b64enc | quote }}

    # Firebase secret
    firebase-secret: {{ default "" .Values.firebaseSecret | b64enc | quote }}

    # Slack secret
    slack-app-id: {{ default "" .Values.slackAppID | b64enc | quote }}
    slack-internal: {{ default "" .Values.slackInternal | b64enc | quote }}
    slack-app-secret: {{ default "" .Values.slackAppSecret | b64enc | quote }}

    # Segment secret
    segment-key: {{ default "" .Values.segmentKey | b64enc | quote }}

    # NewRelic license
    newrelic-license-key: {{ default "" .Values.newrelicLicenseKey | b64enc | quote }} 

    # Rollbar access token
    rollbar-access-token: {{ default "" .Values.rollbarAccessToken | b64enc | quote }}  

    # Loggly
    loggly-token: {{ default "" .Values.logglyToken | b64enc | quote }} 

    # TLS sign client key
    tls-client-key: {{ default "" .Values.tlsClientKey | b64enc | quote }}

    # walkme url
    walkme-url: {{ default "" .Values.walkmeUrl | b64enc | quote }}

    # LaunchDarkly key
    launchdarkly-key: {{ default "" .Values.launchdarklyKey | b64enc | quote }} 

    # CFCR Registry auth key
    reg-auth-api-key: {{ default "" .Values.registryAuthKey | b64enc | quote }}

    # CFCR Registry auth key
    registry-admin-token: {{ default "" .Values.registryAdminToken | b64enc | quote }}
