apiVersion: v1
description: Codefresh CD pipeline management platform for Kubernetes
name: codefresh
version: 0.6.35
keywords:
- codefresh
- kubernetes
- pipeline
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
- https://github.com/codefresh-io/cf-helm
maintainers:
- name: Alexei Ledenev
  email: alexei@codefresh.io
appVersion: 0.6
