apiVersion: v2
description: Helm Chart for Codefresh On-Prem
name: codefresh
version: 2.2.0-rc.4
keywords:
  - codefresh
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
  - https://github.com/codefresh-io/cf-helm
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
appVersion: 2.2.0
annotations:
  artifacthub.io/alternativeName: "codefresh-onprem"
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: Onprem 2.2.0-rc.4 pre-release
dependencies:
  - name: cf-common
    repository: oci://quay.io/codefresh/charts
    version: 0.16.0
  - name: internal-gateway
    repository: oci://quay.io/codefresh/charts
    version: "0.3.1"
    condition: internal-gateway.enabled
  - name: consul
    version: 10.14.4
    repository: https://charts.bitnami.com/bitnami
    condition: consul.enabled
  - name: mongodb
    version: 14.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled,mongo.enabled,global.mongoDeploy
  - name: postgresql
    version: 12.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: postgresql-ha
    version: 12.0.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql-ha.enabled
  - name: redis
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: redis-ha
    repository: https://dandydeveloper.github.io/charts
    version: 4.23.0
    condition: redis-ha.enabled
  - name: rabbitmq
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: nats
    version: 7.10.5
    repository: https://charts.bitnami.com/bitnami
    condition: nats.enabled
  - name: builder
    repository: oci://quay.io/codefresh/charts
    condition: builder.enabled
    version: 1.3.0
  - name: runner
    repository: oci://quay.io/codefresh/charts
    condition: runner.enabled
    version: 1.3.0
  - name: ingress-nginx
    version: 4.8.4
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: cluster-providers
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cluster-providers.enabled
  - name: kube-integration
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: kube-integration.enabled
  - name: charts-manager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: charts-manager.enabled
  - name: cfsign
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfsign.enabled
  - name: tasker-kubernetes
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: tasker-kubernetes.enabled
  - name: context-manager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: context-manager.enabled
  - name: pipeline-manager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: pipeline-manager.enabled
  - name: gitops-dashboard-manager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: gitops-dashboard-manager.enabled
  - name: cfapi
    alias: cfapi
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi.enabled
  - name: cfapi
    alias: cfapi-internal
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-internal.enabled
  - name: cfapi
    alias: cfapi-ws
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-ws.enabled
  - name: cfapi
    alias: cfapi-admin
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-admin.enabled
  - name: cfapi
    alias: cfapi-endpoints
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-endpoints.enabled
  - name: cfapi
    alias: cfapi-terminators
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-terminators.enabled
  - name: cfapi
    alias: cfapi-sso-group-synchronizer
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-sso-group-synchronizer.enabled
  - name: cfapi
    alias: cfapi-buildmanager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-buildmanager.enabled
  - name: cfapi
    alias: cfapi-cacheevictmanager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-cacheevictmanager.enabled
  - name: cfapi
    alias: cfapi-eventsmanagersubscriptions
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-eventsmanagersubscriptions.enabled
  - name: cfapi
    alias: cfapi-kubernetesresourcemonitor
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-kubernetesresourcemonitor.enabled
  - name: cfapi
    alias: cfapi-environments
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-environments.enabled
  - name: cfapi
    alias: cfapi-gitops-resource-receiver
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-gitops-resource-receiver.enabled
  - name: cfapi
    alias: cfapi-downloadlogmanager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-downloadlogmanager.enabled
  - name: cfapi
    alias: cfapi-teams
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-teams.enabled
  - name: cfapi
    alias: cfapi-kubernetes-endpoints
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-kubernetes-endpoints.enabled
  - name: cfapi
    alias: cfapi-test-reporting
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-test-reporting.enabled
  - name: cfui
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cfui.enabled
  - name: k8s-monitor
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: k8s-monitor.enabled
  - name: runtime-environment-manager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: runtime-environment-manager.enabled
  - name: cf-broadcaster
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: cf-broadcaster.enabled
  - name: helm-repo-manager
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: helm-repo-manager.enabled
  - name: hermes
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
  - name: nomios
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
  - name: cronus
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
  - name: cf-platform-analytics
    alias: cf-platform-analytics-platform
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: cf-platform-analytics
    alias: cf-platform-analytics-etlstarter
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: argo-platform
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: argo-hub-platform
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: codefresh-tunnel-server
    version: "*"
    repository: oci://quay.io/codefresh/charts
    condition: codefresh-tunnel-server.enabled
  - name: cf-oidc-provider
    repository: oci://quay.io/codefresh/charts
    version: "*"
    condition: cf-oidc-provider.enabled