dependencies:
  - name: consul
    version: 1.1.2
    repository: file://pv-charts/consul
    condition: consul.enabled
    tags:
      - infra
  - name: mongodb
    version: 0.4.12
    repository: file://pv-charts/mongodb
    condition: mongo.enabled,global.mongoDeploy
    tags:
      - infra
  - name: postgresql
    version: 0.7.1
    repository: file://pv-charts/postgresql
    condition: postgresql.enabled
    tags:
      - infra
  - name: redis
    version: 0.8.0
    repository: file://pv-charts/redis
    condition: redis.enabled
    tags:
      - infra
  - name: rabbitmq
    version: 0.6.15
    repository: file://pv-charts/rabbitmq
    condition: rabbitmq.enabled
    tags:
      - infra
  - name: nats
    version: 0.1.1
    repository: file://../nats
    condition: nats.enabled
    tags:
      - infra
      - saas
  - name: builder
    repository: file://local-charts/builder
    condition: builder.enabled
    version: 0.1.4
    tags:
      - infra
  - name: runner
    repository: file://local-charts/runner
    condition: runner.enabled
    version: 0.1.4
    tags:
      - infra
  - name: registry
    version: 0.1.2
    repository: file://../registry
    condition: registry.enabled
    tags:
      - infra
  - name: ingress
    version: 0.1.10
    repository: 'file://../ingress'
    condition: ingress.enabled
  - name: cluster-providers
    version: "*"
    repository: http://chartmuseum.codefresh.io/cluster-providers
  - name: kube-integration
    version: "*"
    repository: http://chartmuseum.codefresh.io/kube-integration
  - name: accounts-referrals
    version: "*"
    repository: http://chartmuseum.codefresh.io/accounts-referrals
    tags:
    - saas
  - name: charts-manager
    version: "*"
    repository: http://chartmuseum.codefresh.io/charts-manager
    tags:
    - saas
    - infra
  - name: mailer
    version: "*"
    repository: http://chartmuseum.codefresh.io/mailer
    tags:
    - saas
  - name: payments
    version: "*"
    repository: http://chartmuseum.codefresh.io/payments
    tags:
    - saas
  - name: cfsign
    version: "*"
    repository: http://chartmuseum.codefresh.io/cfsign
    condition: cfsign.enabled
    tags:
    - saas
    - infra
  - name: segment-reporter
    version: "*"
    repository: http://chartmuseum.codefresh.io/segment-reporter
    tags:
    - saas
  - name: salesforce-reporter
    version: "*"
    repository: http://chartmuseum.codefresh.io/salesforce-reporter
    tags:
    - saas
  - name: tasker-kubernetes
    version: "*"
    repository: http://chartmuseum.codefresh.io/tasker-kubernetes
    tags:
    - saas
    - infra
  - name: context-manager
    version: "*"
    repository: http://chartmuseum.codefresh.io/context-manager
    tags:
    - saas
    - infra
  - name: pipeline-manager
    version: "*"
    repository: http://chartmuseum.codefresh.io/pipeline-manager
    tags:
    - saas
    - infra
  - name: cfapi
    version: "*"
    repository: http://chartmuseum.codefresh.io/cfapi
    condition: cfapi.enabled
    tags:
    - saas
    - infra
  - name: cfui
    version: "*"
    repository: http://chartmuseum.codefresh.io/cfui
    condition: cfui.enabled
    tags:
    - saas
    - infra
# - name: k8s-monitor
#   version: ^4.0.0
#   repository: http://chartmuseum.codefresh.io
#   condition: cfui.enabled
#   tags:
#     - saas
#     - infra
  - name: onboarding-status
    version: "*"
    repository: http://chartmuseum.codefresh.io/onboarding-status
    condition: onboarding-status.enabled
    tags:
    - saas
    - infra
  - name: runtime-environment-manager
    version: "*"
    repository: http://chartmuseum.codefresh.io/runtime-environment-manager
    condition: runtime-environment-manager.enabled
    tags:
    - saas
    - infra
  - name: cf-broadcaster
    version: "*"
    repository: http://chartmuseum.codefresh.io/cf-broadcaster
    condition: cf-broadcaster.enabled
    tags:
    - saas
    - infra
  - name: helm-repo-manager
    version: "*"
    repository: http://chartmuseum.codefresh.io/helm-repo-manager
    condition: helm-repo-manager.enabled
    tags:
    - helm
    - chartmuseum
  - name: hermes
    version: "*"
    repository: http://chartmuseum.codefresh.io/hermes
    condition: hermes.enabled
    tags:
    - trigger
    - trigger-manager
  - name: nomios
    version: "*"
    repository: http://chartmuseum.codefresh.io/nomios
    condition: hermes.enabled
    tags:
    - trigger
    - event-provider
    - registry
    - dockerhub
  - name: cronus
    version: "*"
    repository: http://chartmuseum.codefresh.io/cronus
    condition: hermes.enabled
    tags:
    - trigger
    - event-provider
    - cron
