dependencies:
- name: consul
  version: 0.3.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - infra
- name: mongodb
  version: 0.4.12
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - infra
- name: postgresql
  version: 0.7.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - infra
- name: redis
  version: 0.8.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - infra
- name: rabbitmq
  version: 0.5.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - infra
- name: nats
  version: 0.1.0
  repository: file://../nats
  tags:
    - infra
    - nats
- name: builder
  repository: file://charts/builder
  version: 0.1.2
  tags:
    - infra
    - builder
- name: runner
  repository: file://charts/runner
  version: 0.1.2
  tags:
    - infra
    - runner
- name: registry
  repository: file://../registry
  version: 0.1.0
  tags:
    - infra
- name: ingress
  version: 0.1.0
  repository: file://../ingress
  condition: ingress.enabled
- name: cfruntime
  repository: file://charts/cfruntime
  version: 0.1.2
  tags:
    - old-scheduler
- name: cluster-providers
  version: 0.0.1
  repository: file://charts/cluster-providers
- name: multiple-clusters
  version: 0.0.1
  repository: file://charts/multiple-clusters
- name: kube-integration
  version: 0.0.1
  repository: file://charts/kube-integration
- name: accounts-referrals
  version: 0.0.1
  repository: file://charts/accounts-referrals
  tags:
    - saas
- name: mailer
  version: 0.0.1
  repository: file://charts/mailer
  tags:
    - saas
- name: payments
  version: 0.1.2
  repository: file://charts/payments
  tags:
    - saas
- name: cfsign
  version: 0.1.0
  repository: file://charts/cfsign
  tags:
    - saas
- name: internal-status-page
  version: 0.0.1
  repository: file://charts/internal-status-page
  tags:
    - saas
- name: segment-reporter
  version: 0.0.1
  repository: file://charts/segment-reporter
  tags:
    - saas
- name: workflow-baseline-invoker
  version: 0.0.1
  repository: file://charts/workflow-baseline-invoker
  tags:
    - saas
