version: "1.0"

stages:
  - get_img_list
  - generate_and_send_report

steps:
  clone:
    type: "git-clone"
    repo: "codefresh-io/onprem-images"
    git: "${{GIT_CONTEXT}}"
    revision: "master"
    stage: get_img_list

  get_images_list:
    description: "Gets a list of images for a certain onprem release"
    image: alpine/helm
    working_directory: ${{clone}}
    commands:
      - apk add bash
      - ./get-img-list.sh --repo ${CHANNEL} --version ${ONPREM_VERSION} > ${{IMG_LIST_FILE}}
      - cat ${{IMG_LIST_FILE}}
    stage: get_img_list

  get_github_token:
    stage: generate_and_send_report
    image: codefresh/cli
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get contexts --type git.github ${GIT_CONTEXT} --decrypt -o json | jq -r '.spec.data.auth.password') || return 1

  generate_scan_report:
    description: "Scans the images in the provided list and generates a report file"
    image: codefreshio/onprem-vuln-reporter
    working_directory: IMAGE_WORK_DIR
    shell: bash
    stage: generate_and_send_report
    commands:
      - ./generate_scan_report.sh

  upload_report_to_S3:
    image: mesosphere/aws-cli
    stage: generate_and_send_report
    commands:
      - aws s3 cp ${SCAN_REPORT_FILE} s3://${S3_BUCKET_NAME}/onprem/${ONPREM_VERSION}.txt