apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-consul-ui-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  initContainers:
    - name: test-framework
      {{- if .Values.global.privateRegistry }}
      image: {{ .Values.global.dockerRegistry }}codefresh/bats:0.4.0
      {{- else }}
      image: dduportal/bats:0.4.0
      {{- end }}
      command:
      - "bash"
      - "-c"
      - |
        set -ex
        # copy bats to tools dir
        cp -R /usr/local/libexec/ /tools/bats/
      volumeMounts:
      - mountPath: /tools
        name: tools
  containers:
    - name: {{ .Release.Name }}-ui-test
      {{- if .Values.global.privateRegistry }}
      image: {{ .Values.global.dockerRegistry }}{{ trimPrefix "quay.io/" .Values.test.image }}:{{ .Values.test.imageTag }}
      {{- else }}
      image: {{ .Values.test.image }}:{{ .Values.test.imageTag }}
      {{- end }}
      command: ["/tools/bats/bats", "-t", "/tests/run.sh"]
      volumeMounts:
      - mountPath: /tests
        name: tests
        readOnly: true
      - mountPath: /tools
        name: tools
  volumes:
  - name: tests
    configMap:
      name: {{ template "consul.fullname" . }}-tests
  - name: tools
    emptyDir: {}
  restartPolicy: Never
