{{- if and (index .Values "argo-platform" "enabled") (not .Values.global.mongoSkipUserCreation) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-argo-platform-create-db
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: {{ template "fullname" . }}-argo-platform-create-db
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
    spec:
      {{- if .Values.global.privateRegistry }}
      imagePullSecrets:
        - name: "{{ .Release.Name }}-{{ .Values.global.codefresh }}-registry"
      {{- end }}
      containers:
      - name: {{ template "fullname" . }}-argo-platform-create-db
        {{- if .Values.global.privateRegistry }}
        image: "{{ .Values.global.dockerRegistry }}{{ .Values.global.mongodbImage }}"
        {{- else }}
        image: {{ .Values.global.mongodbImage }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        env:
          {{- if .Values.global.env }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end}}
          {{- end}}
          - name: MONGODB_ROOT_USER
            value: {{ .Values.global.mongodbRootUser }}
          - name: MONGODB_ROOT_PASSWORD
            value: {{ .Values.global.mongodbRootPassword }}
          - name: MONGODB_URI
            value: {{ .Values.global.argoPlatformMongoUri | quote }}
          - name: MONGODB_DATABASE
            value: {{ .Values.global.argoPlatformMongoDatabase }}
          - name: MONGODB_USER
            value: {{ .Values.global.argoPlatformMongodbUsername }}
          - name: MONGODB_PASSWORD
            value: {{ .Values.global.argoPlatformMongodbPassword }}
        command:
          - "/bin/bash"
          - "-exc"
          - |
{{ .Files.Get (print "files/on-prem/mongoCreateDbJobScript" ) | indent 12  }}
      restartPolicy: Never
{{- end }}
