{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled (not .Values.ingress.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codefresh.fullname" . }}-{{ .Values.ingress.tls.secretName }}
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- $cert := buildCustomCert (required "A valid .Values.ingress.tls.cert is required!" .Values.ingress.tls.cert) (required "A valid .Values.ingress.tls.key is required!" .Values.ingress.tls.key) }}
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- end }}