{{ $libTemplateName := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "codefresh.fullname" . }}
  labels:
    {{ include "codefresh.labels" . | nindent 4 }}
data:
  # new MONGODB_* secrets
  MONGODB_HOST: {{ coalesce .Values.global.mongodbHost | b64enc }}
  MONGODB_PASSWORD: {{ coalesce .Values.global.mongodbPassword | b64enc }}
  MONGODB_USER: {{ coalesce .Values.global.mongodbUser | b64enc }}
  MONGODB_OPTIONS: {{ coalesce .Values.global.mongodbOptions | b64enc }}
  MONGODB_DATABASE: {{ coalesce .Values.global.mongodbDatabase | default "codefresh" | b64enc }}
  MONGODB_PROTOCOL: {{ coalesce .Values.global.mongodbProtocol | default "mongodb" | b64enc }}

 # legacy MONGODB_* secrets
  MONGODB_ROOT_USER: {{ coalesce .Values.global.mongodbRootUser .Values.seed.mongoSeedJob.mongodbRootUser | b64enc }}
  MONGODB_ROOT_PASSWORD: {{ urlquery (coalesce .Values.global.mongodbRootPassword .Values.seed.mongoSeedJob.mongodbRootPassword) | b64enc }}
  MONGO_URI: {{ .Values.global.mongoURI | default "empty" | b64enc}}
  MONGO_URI_RE_MANAGER: {{ include (printf "%s.classic.calculateMongoUri" $libTemplateName) (dict "dbName" "runtime-environment-manager" "mongoURI" .Values.global.mongoURI) | default "empty" | b64enc }}
  MONGODB_RE_DATABASE: {{ printf "%s" "runtime-environment-manager" | b64enc }}

  POSTGRES_USER: {{ coalesce .Values.global.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ coalesce .Values.global.postgresPassword | b64enc }}
  POSTGRES_SEED_USER: {{ (coalesce .Values.seed.postgresSeedJob.postgresUser .Values.global.postgresSeedJob.postgresUser) | default .Values.global.postgresUser | b64enc}}
  POSTGRES_SEED_PASSWORD: {{ (coalesce .Values.seed.postgresSeedJob.postgresPassword .Values.global.postgresSeedJob.postgresPassword) | default .Values.global.postgresPassword | b64enc }}
  POSTGRES_HOSTNAME: {{ default (printf "%s-%s" .Release.Name .Values.global.postgresService) .Values.global.postgresHostname | b64enc }}
  POSTGRES_PORT: {{ printf "%v" .Values.global.postgresPort | b64enc }}
  POSTGRES_DATABASE: {{ .Values.global.postgresDatabase | default "codefresh" | b64enc }}
