apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
spec:
  {{- if .Values.service }}
  type: {{ default "ClusterIP" .Values.service.type | quote }}
  {{- end }}
  ports:
  - name: "http"
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.targetPort }}
  - name: "internal-api"
    port: {{ .Values.internalPort }}
    protocol: TCP
    targetPort: {{ .Values.targetInternalPort }}
  selector:
    app: {{ template "fullname" . }}